#!/bin/bash

SRC_ARCH="amd64"
DEST_ARCHES="amd64"

# Cycle trough the the arches
for DEST_BUILD_ARCH in ${DEST_ARCHES}
do
    if [ ${DEST_BUILD_ARCH} == "amd64" ]; then
        echo 'qemu-user-static: Download not required for amd64'
        continue
    elif [ ${DEST_BUILD_ARCH} == "arm32v7" ]; then
        QEMU_USER_STATIC_ARCH="arm"
    elif [ ${DEST_BUILD_ARCH} == "arm64v8" ]; then
        QEMU_USER_STATIC_ARCH="aarch64"
    else 
        echo "DEBUG: DEST_BUILD_ARCH not referenced"
        exit 1
    fi
    
    QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
    QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
        | grep 'name.*v[0-9]' \
        | head -n 1 \
        | cut -d '"' -f 4)

    curl -SL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz" \
        | tar xzv
done

echo "DEBUG: Exiting post_checkout"

exit 0
