#!/bin/bash

# https://github.com/ichbestimmtnicht/docker-autobuild-release
# Template created 2020 by Ludwig Werner Döhnert
# This work is licensed under the Creative Commons Attribution 4.0 International License.
# To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/.

source hooks/env.sh

# Get the manifest-tool
wget -cO - https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64 > manifest-tool

chmod +x manifest-tool

# Cycle trough the the arches and push the images
echo "SCRIPT_INFO: Push the docker images per arch ${DEST_ARCHES}"
for SR_DEST_BUILD_ARCH in ${DEST_ARCHES}
do
    docker push ${IMAGE_NAME}-${SR_DEST_BUILD_ARCH}
    echo "SCRIPT INFO: ${IMAGE_NAME}-${SR_DEST_BUILD_ARCH} pushed"
done

# Push the manifest

echo "SCRIPT_INFO: Pushing manifest."

./manifest-tool push from-spec auto-docker-manifest.yaml
rm -f auto-docker-manifest.yaml

echo "SCRIPT_INFO: Pushed manifest."

exit 0
