#!/bin/bash

apt-get update && apt-get install wget -y -q

# DEBUG
cat auto-docker-manifest.yaml

# Get the manifest-tool
wget -cO - https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64 > manifest-tool

chmod +x manifest-tool

echo "Push the manifest"

./manifest-tool push from-spec auto-docker-manifest.yaml
rm -f auto-docker-manifest.yaml

echo "DEBUG: Exiting push"

exit 0
